//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.5.3
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace CandidContribs.Core.Models.Published
{
	/// <summary>AutoRoundSettings</summary>
	[PublishedModel("autoRoundSettings")]
	public partial class AutoRoundSettings : PublishedContentModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		public new const string ModelTypeAlias = "autoRoundSettings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<AutoRoundSettings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public AutoRoundSettings(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Maximum Timeout: In seconds
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		[ImplementPropertyType("maximumTimeout")]
		public int MaximumTimeout => this.Value<int>("maximumTimeout");

		///<summary>
		/// Minimum Time Out: In seconds
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		[ImplementPropertyType("minimumTimeOut")]
		public int MinimumTimeOut => this.Value<int>("minimumTimeOut");

		///<summary>
		/// Prefered Timeout: In seconds Bot will try to skew random between min and max towards this number
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		[ImplementPropertyType("preferedTimeout")]
		public int PreferedTimeout => this.Value<int>("preferedTimeout");

		///<summary>
		/// Prefered Timeout Skew Percentage: between 0 and 100, values over this will be reduced to these values
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		[ImplementPropertyType("preferedTimeoutSkewPercentage")]
		public int PreferedTimeoutSkewPercentage => this.Value<int>("preferedTimeoutSkewPercentage");
	}
}
