//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.5.3
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder.Embedded;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Events page</summary>
	[PublishedModel("eventsPage")]
	public partial class EventsPage : PublishedContentModel, IMetaTags
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		public new const string ModelTypeAlias = "eventsPage";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		public new static IPublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<EventsPage, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public EventsPage(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// About content: appears alongside the image in 'about' section (image currently hard-coded)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		[ImplementPropertyType("aboutContent")]
		public global::System.Web.IHtmlString AboutContent => this.Value<global::System.Web.IHtmlString>("aboutContent");

		///<summary>
		/// Entries
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		[ImplementPropertyType("part1Entries")]
		public global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.DayScheduleEntry> Part1Entries => this.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.DayScheduleEntry>>("part1Entries");

		///<summary>
		/// Start date
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		[ImplementPropertyType("part1StartDate")]
		public global::System.DateTime Part1StartDate => this.Value<global::System.DateTime>("part1StartDate");

		///<summary>
		/// Entries
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		[ImplementPropertyType("part2Entries")]
		public global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.DayScheduleEntry> Part2Entries => this.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Web.PublishedModels.DayScheduleEntry>>("part2Entries");

		///<summary>
		/// Start date
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		[ImplementPropertyType("part2StartDate")]
		public global::System.DateTime Part2StartDate => this.Value<global::System.DateTime>("part2StartDate");

		///<summary>
		/// Sign up content: appears above the email input in 'Sign Up' section
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		[ImplementPropertyType("signUpContent")]
		public global::System.Web.IHtmlString SignUpContent => this.Value<global::System.Web.IHtmlString>("signUpContent");

		///<summary>
		/// Speakers
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		[ImplementPropertyType("speakers")]
		public global::System.Collections.Generic.IEnumerable<global::Umbraco.Core.Models.PublishedContent.IPublishedContent> Speakers => this.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Core.Models.PublishedContent.IPublishedContent>>("speakers");

		///<summary>
		/// Description: meta and OG description,  has default value
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription => global::Umbraco.Web.PublishedModels.MetaTags.GetMetaDescription(this);

		///<summary>
		/// Keywords: meta keywords, has default value
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		[ImplementPropertyType("metaKeywords")]
		public string MetaKeywords => global::Umbraco.Web.PublishedModels.MetaTags.GetMetaKeywords(this);

		///<summary>
		/// Title: browser and OG title, defaults to node name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		[ImplementPropertyType("metaTitle")]
		public string MetaTitle => global::Umbraco.Web.PublishedModels.MetaTags.GetMetaTitle(this);

		///<summary>
		/// Open Graph image: Leave blank to use the default image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.5.3")]
		[ImplementPropertyType("openGraphImage")]
		public global::Umbraco.Core.Models.PublishedContent.IPublishedContent OpenGraphImage => global::Umbraco.Web.PublishedModels.MetaTags.GetOpenGraphImage(this);
	}
}
